### ISSUE TITLE
Payment Provider callback not found (404)

### ISSUE THREAD

**Issue by philipdanielhayton** [umbraco/Umbraco.Commerce.PaymentProviders.Stripe#1]
Hi guys,

I've recently upgraded to Umbraco 12 and migrated from Vendr to Umbraco Commerce.

I'm having issues with the Stripe payment provider, the webhook callback is throwing a 404. I've double checked this on a completely clean install of Umbraco 12, Umbraco Commerce 12, and the Stripe Payment provider. 

If I try to hit the callback in a browser it throws a 404, e.g: `https://localhost:44315/umbraco/umbracocommerce/payment/callback/stripe-checkout/215c4c97-85c5-4227-b0cd-0189b58b6f5b/`

Calling a similar URL from a project that on Umbraco 11 + Vendr returns OK 200.

Is there something I'm missing in my implementation, or is it a bug?

Cheers

Phil

**Comment by philipdanielhayton** [comment]
Hahaha good news, I've just realized what it is. It's just a typo in the docs 🤦🏻‍♂️

The callback should be `/umbraco/commerce/` instead of `/umbraco/umbracocommerce/`.

**Comment by mattbrailsford** [comment]
Thanks for the head, I think this docs PR i've just created should fix this for people in future https://github.com/umbraco/UmbracoDocs/pull/5329 👍
